# Generated by Django 2.0.5 on 2018-06-12 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180610_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='trip_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.ManyToManyField(related_name='country_fk', to='webapp.Country'),
        ),
    ]
