# Generated by Django 2.0.5 on 2018-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180612_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.ManyToManyField(related_name='countryFk', to='webapp.Country'),
        ),
    ]
