# Generated by Django 2.0.5 on 2018-06-12 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180612_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
