# Generated by Django 2.0.5 on 2019-03-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190225_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.RemoveField(
            model_name='transactioninvolvment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactioninvolvment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionlabels',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='TransactionInvolvment',
        ),
        migrations.DeleteModel(
            name='TransactionLabels',
        ),
    ]
